### ISSUE TITLE
GUI e Menu de Jogo

### ISSUE THREAD

**Issue by mildspice** [SterbenCyrodiil/ProjetoED#2]
Estou com alguma dificuldade em arranjar ideias para o menu do jogo.
Atualmente tenho esta lista:
- PLAY
  - ESCOLHER DIFICULDADE
    - SIMULAR JOGO (warning spoilers!)
    - DETALHES DO JOGADOR (nome, etc. para as classificações)
- VISUALIZAR MAPA 
  NOTA: ainda a decidir como vai ficar feito, pode-se mostrar simplemente as conexões entre as várias divisões sem mostrar as saídas para o exterior?
- CARREGAR MAPA
  NOTA: ficheiro JSON, PLAY redirecionado para aqui se não houver mapa carregado

E graficamente:
![imagem](https://user-images.githubusercontent.com/44165718/73194915-d36d3880-4124-11ea-99de-72cbb51be92e.png)

Ideias?

**Comment by SterbenCyrodiil** [comment]
Sim, o nome é obrigatório devido às Classificações. Não creio que haja mais alguma coisa estritamente obrigatória que envolva input do utilizador.
Na parte de visualização de um mapa, o que estava a "imaginar" seria uma visualização 2d do aposento, com o utilizador lá dentro. Depois, numa espécie de fog of war, ele poderia ver que existe várias ligações, ou seja, as portas, para outras divisões. Quando entrasse numa divisão, dava-lhe simplesmente o nome da divisão, mais o "jump-scare" expectável caso tenha fantasma. 
Não se indicaria nunca qual seria a divisão na porta, apenas saberia que ela existia... Para onde? Entra, e descobre. 
De resto, creio que estará apropriado

**Comment by mildspice** [comment]
Acho que já tenho uma ideia definitiva para o mapa então.

Resumidamente, mostra-se uma divisão de cada vez com portas que dão para as divisões vizinhas. Sabemos onde estamos, não sabemos para onde vamos. Assim, mesmo que a porta seja uma saída, o utilizador não sabe até a atravessar!

Para ajudar também se disponibiliza uma lista com o nome de cada divisão e cada uma das suas conexões. Pode variar dependendo da dificuldade também.
